name: Scrape traffic (slim)

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Scrape
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      run: |
        now=$(date +%s)
        # Oakland to Golden Gate Bridge
        curl "https://maps.googleapis.com/maps/api/directions/json?origin=place_id:ChIJQabAAlSEj4ARYHQBAw8MY7A&destination=place_id:ChIJw____96GhYARCVVwg5cT7c0&departure_time=now&key=$GOOGLE_MAPS_API_KEY" | jq '{id: "oakland-goldengate", duration_in_traffic: .routes[0].legs[0].duration_in_traffic.value}' > oakland-to-goldengate-slim_${now}.json
        sleep 3
        # Golden Gate Bridge to Oakland
        curl "https://maps.googleapis.com/maps/api/directions/json?origin=place_id:ChIJw____96GhYARCVVwg5cT7c0&destination=place_id:ChIJQabAAlSEj4ARYHQBAw8MY7A&departure_time=now&key=$GOOGLE_MAPS_API_KEY" | jq '{id: "goldengate-oakland", duration_in_traffic: .routes[0].legs[0].duration_in_traffic.value}' > goldengate-to-oakland-slim_${now}.json
        sleep 3
    - name: Commit and push
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "${timestamp}" || exit 0
        git pull --rebase
        git push