name: Scrape traffic sample

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scraper:
    runs-on: ubuntu-latest
    steps:
    - name: Scrape
      env:
        GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      run: |
        set -euo pipefail
        now=$(date +%s)
        mkdir -p data
        # Oakland to Golden Gate Bridge
        curl --fail --silent --show-error "https://maps.googleapis.com/maps/api/directions/json?origin=place_id:ChIJQabAAlSEj4ARYHQBAw8MY7A&destination=place_id:ChIJw____96GhYARCVVwg5cT7c0&departure_time=now&key=$GOOGLE_MAPS_API_KEY" | jq '{id: "oakland-goldengate", duration_in_traffic: .routes[0].legs[0].duration_in_traffic.value}' > ./data/oakland-to-goldengate-slim_${now}.json
        sleep 3
        # Golden Gate Bridge to Oakland
        curl --fail --silent --show-error "https://maps.googleapis.com/maps/api/directions/json?origin=place_id:ChIJw____96GhYARCVVwg5cT7c0&destination=place_id:ChIJQabAAlSEj4ARYHQBAw8MY7A&departure_time=now&key=$GOOGLE_MAPS_API_KEY" | jq '{id: "goldengate-oakland", duration_in_traffic: .routes[0].legs[0].duration_in_traffic.value}' > ./data/goldengate-to-oakland-slim_${now}.json
        sleep 3
    - uses: actions/upload-artifact@v4
      with:
        name: traffic-sample
        path: data/*.json
        retention-days: 30
